### PR TITLE
Fixing OSS Sonatype deployment

### PR DESCRIPTION
**Pull request by ilgrosso**
With current settings, SNAPSHOT deployment to OSS Sonatype repo does not work.

### CODE REVIEW

**Comment by MarcGiffing** [comment]
Thanks for the PR but the change of the URL was wrong. s01 is correct. I've deployed the SNAPSHOT version

**Comment by ilgrosso** [comment]
Thank you @MarcGiffing 
I was suggesting such a change based on what I have on other repos, but I see it worked with yours, so ok :+1:

**Comment by ilgrosso** [comment]
Sorry but I keep getting errors like:

```
Could not find artifact com.giffing.wicket.spring.boot.starter:wicket-spring-boot-starter:jar:4.0.0-SNAPSHOT in sonatype (https://oss.sonatype.org/content/repositories/snapshots) 
```

**Comment by ilgrosso** [comment]
Ok, I guess this was because of https://central.sonatype.org/news/20210223_new-users-on-s01/

**Comment by MarcGiffing** [comment]
Yes, but I've changed by choice due to the overloading problems of the 'old' server. The deployment on the s01 runs really  smoothly :thumbsup:

**Pull request closed without merging**
