### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by martin-g** [comment]
I am not able to load `/first-page` in the examples. It fails with Wicket Component queueing problem. I guess the same is happening for you too?

**Comment by martin-g** [comment]
I see no need to provide `HomePage` and `LoginPage` in the project. I think every project (like the example) should provide those.
I didn't want to make this change in this PR before discussing it with you.

**Comment by MarcGiffing** [comment]
I've fixed the problem with the /first-page. I've added a postfix 'Border' in the LabledFormBroder which was not added in the markup. I think the test pages FirstPage and SecondPage can be removed in favor of the Customers pages.

Yes, there is no need for the HomePage and LoginPage. My intention was to provide a full working application without more configuration needs. Especially for users which are not familiar with wicket. But you're right. There are useless and maybe also a security problem if a fixed LoginPage is provided which can't be changed.

**Comment by martin-g** [comment]
:+1:

**Pull request merged**
